app/__init__.py
from flask import Flask
from config import Config
from .site.routes import site
from .authentication.routes import auth
from .api.routes import api

from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from models import db as root_db, login_manager, ma
from flask_cors import CORS
from helpers import JSONEncoder

app = Flask(__name__)
CORS(app)

app.register_blueprint(site)
app.register_blueprint(auth)
app.register_blueprint(api)

app.json_encoder = JSONEncoder
app.config.from_object(Config)
root_db.init_app(app)
login_manager.init_app(app)
ma.init_app(app)
migrate = Migrate(app, root_db)

app/api/routes.py
from flask import Blueprint, jsonify, request, render_template
from helpers import token_required
from models import db, User, Books, book_schema, books_schema

api = Blueprint('api', __name__, url_prefix='/api')


@api.route('/getdata')
def getdata():
    return {'some': 'value'}

@api.route('/books', methods=['POST'])
@token_required
def create_book(current_user_token):
    title = request.json['title']
    author = request.json['author']
    genre = request.json['genre']
    isbn = request.json['isbn']
    hardcover = request.json['hardcover']
    length = request.json['length']
    price = request.json['price']
    user_token = current_user_token.token

    print(f'TESTER: {current_user_token.token}')

    book = Books(title, author, genre, isbn, hardcover, length, price, user_token=user_token)

    db.session.add(book)
    db.session.commit()

    response = book_schema.dump(book)
    return jsonify(response)

@api.route('/books', methods=['GET'])
@token_required
def get_books(current_user_token):
    owner = current_user_token.token
    books = Books.query.filter_by(user_token=owner).all()
    response = books_schema.dump(books)
    return jsonify(response)

@api.route('/books/<id>', methods=['GET'])
@token_required
def get_book(current_user_token, id):
    token = current_user_token.token
    book = Books.query.get(id)
    response = book_schema.dump(book)
    return jsonify(response)

    
@api.route('/books/<id>', methods=['POST', 'PUT'])
@token_required
def update_book(current_user_token, id):
    book = Books.query.get(id)
    book.title = request.json['title']
    book.author = request.json['author']
    book.genre = request.json['genre']
    book.isbn = request.json['isbn']
    book.hardcover = request.json['hardcover']
    book.length = request.json['length']
    book.price = request.json['price']
    book.user_token = current_user_token.token

    db.session.commit()
    response = book_schema.dump(book)
    return jsonify(response)

@api.route('/books/<id>', methods=['DELETE'])
@token_required
def delete_book(current_user_token, id):
    book = Books.query.get(id)
    db.session.delete(book)
    db.session.commit()

    response = book_schema.dump(book)
    return jsonify(response)

app/authentication/routes.py
from forms import UserLoginForm, UserSignUpForm
from models import User, db, check_password_hash
from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import login_user, logout_user, login_required, current_user, LoginManager

auth = Blueprint('auth', __name__, template_folder='auth_templates')


@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    form = UserSignUpForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            first_name = form.first_name.data
            last_name = form.last_name.data
            password = form.password.data

            user = User(first_name, last_name, email, password=password)
            db.session.add(user)
            db.session.commit()

            flash(f'You have successfully created a user account {email}', 'user-created')

            return redirect(url_for('site.home'))
    except:
        raise Exception('Invalid Form Data: Please Check Your Form')
    return render_template('sign_up.html', form=form)

@auth.route('/signin', methods=['GET', 'POST'])
def signin():
    form = UserLoginForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            

            logged_user = User.query.filter(User.email == email).first()

            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You were successfully logged in.', 'auth-success')
                return redirect(url_for('site.home'))
            else:
                flash('Your email/password is incorrect', 'auth-failed')
                return redirect(url_for('auth.signin'))
    except:
        raise Exception('Invalid Form Data: Please Check Your Form')
    return render_template('sign_in.html', form=form)

@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('site.home'))

app/site/routes.py
from flask import render_template, flash, redirect, url_for, Blueprint

site = Blueprint('site', __name__, template_folder='site_templates')


@site.route('/')
def home():
    return render_template('index.html')

@site.route("/profile")
def profile():
    return render_template('profile.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
<title>Bookstore</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 fixed-top">
        <div class="container">
            <a href="{{ url_for('site.home')}}" class="navbar-brand">Bookstore</a>
            <button 
                class="navbar-toggler" 
                type="button" 
                data-bs-toggle="collapse" 
                data-bs-target="#navmenu"
            ><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navmenu">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a href="{{ url_for('site.home')}}" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('site.profile')}}" class="nav-link">Profile</a>
                    </li>
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{{ url_for('auth.logout')}}" class="nav-link">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a href="{{ url_for('auth.signin')}}" class="nav-link">Sign In</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('auth.signup')}}" class="nav-link">Sign Up</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}{% endblock %}
<!-- Mysterious placeholder comment! -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/js/bootstrap.min.js"></script>
</body>
</html>